### ISSUE TITLE
Criação das classes principais.

### ISSUE THREAD

**Issue by AlessanBass** [AlessanBass/Projeto_LP3#1]
Início do projeto

Criação das classes principais do projeto.

**Comment by mathiasbrito** [comment]
Indicar sempre os comits referentes ao Issue... basta copiar o número de referência do comit, vc pode achar ele navegando pelo histórico de comits.

**Comment by AlessanBass** [comment]
Se trata dos primeiros passos para a construção do sistema, foram criadas as classes que darão vida ao sistema. Nesse issue as classes foram apenas criadas sem nenhuma implementação.
### Classes criadas

```
App
Escrita
Gastos
GastoParcelado
Leitura
Menu
Pessoa
Usuario
```
Commit referente ao Issue: 72ededa5c508e0d87d20e55310225823e2f57c6b
