### ISSUE TITLE
Implementação das classes

### ISSUE THREAD

**Issue by AlessanBass** [AlessanBass/Projeto_LP3#2]
Começo da programação do sistema.
Todas as classes deverão ser implementadas.

**Comment by mathiasbrito** [comment]
Este issue está marcado como "Done" no quadro do projeto. Porque que ele está feito? quais foram os comits que implementam está função? Comente abaixo, referenciando os comits e feche o Issue, pois quando ele é considerado `Done` é pq está feito, em estando feito o Issue é considerado finalizado e assim deve ser fechado.

**Comment by AlessanBass** [comment]
As classes do issue #1 foram implementadas com atributos e métodos.

Commit referente ao Issue: 72ededa5c508e0d87d20e55310225823e2f57c6b
Nesse commit foi realizado a criação das classes junto com a devida implementação.
