### ISSUE TITLE
Salvar dados inseridos pelo usuário em um arquivo

### ISSUE THREAD

**Issue by AlessanBass** [AlessanBass/Projeto_LP3#3]
Será necessário estudar formas de como salvar dados inseridos pelo usuário em um arquivo externo.
A classe Escrita será utilizada para escrever esses dados.

**Comment by mathiasbrito** [comment]
Dá uma olhada nesse exemplo https://github.com/profmathias/cet-078/tree/master/Aula11-Bibliotecas-Basicas-Arquivos

Note que você pode escrever uma lista com objetos em um arquivo... e depois lê-lo de volta em uma lista...
https://stackoverflow.com/questions/10654236/java-save-object-data-to-a-file

**Comment by AlessanBass** [comment]
Para salvar dos dados inseridos pelo usuário utilizei a classe FileWriter.
Primeiro foi necessário um importe do pacote java.io
```
import  java.io.File ; 
import  java.io.FileWriter ;
import  java.io.IOException ;
import  java.util.Scanner ;`
```

Logo após temos a criação de objetos do tipo Gasto e GastoParcelado e um Scanner para receber a opção caso o usuário tenha comprado parcelado
```
Gastos gastos =  novos  Gastos ();    
GastoParcelado gp =  novo  GastoParcelado ();    
Scanner ler =  novo  Scanner ( Sistema . In);
```
Temos uma chamada de um método "preenche" que será utilizado para capturar os dados sobre as despesas do usuário: 
```
public  void  preenche () {      
  gastos . preencheDados ();     
  int op = ler . nextInt ();      
  if (op ==  1 ) {           
  gp . preenche ();  
} else {   
  gp . setNumDeParcelas ( " 1 " );          
  gp . setParcelasPagas ( " 1 " );  }
 }
```
Finalmente temos o método que escreve no arquivo, importante observar que após cada dado salvo é escrito um ";". Esse parâmetro é importante e será abordado com mais detalhes na parte de #5.

```
public  void  chamarNoArquivo ( File  arq ) throws  IOException {        
    FileWriter fw =  new  FileWriter (arq, true );        
    fw . escrever (gastos . getNome ());       
    fw . escrever ( " ; " );       
    fw . escrever (gastos . getValor ());
    fw . escrever ( " ; " );
    fw . escrever (gp . getNumDeParcelas ()); 
    fw . escrever ( " ; " );      
    fw . escrever (gp . getParcelasPagas ());
    fw . escrever ( " ; " );        
    fw . escrever ( " \ n " );  
    fw . rubor();       
    fw . perto();    
}
``` 
Commit referente ao Issue: 0bfe68c900a2a8e1470672301583266938f23aaf
