### ISSUE TITLE
Tratamento de dados lidos do arquivo

### ISSUE THREAD

**Issue by AlessanBass** [AlessanBass/Projeto_LP3#5]
Na classe Leitura será feita a leitura de dados salvos pelo usuário no arquivo. 
O usuário deseja que seja mostrado o nome do gasto, o valor total do gasto, o parcelamento e o valor de cada parcela (caso tenha sido parcelado), tudo isso com a soma total de todos os gastos daquele mês.

**Comment by mathiasbrito** [comment]
Dá uma olhada nesse exemplo https://github.com/profmathias/cet-078/tree/master/Aula11-Bibliotecas-Basicas-Arquivos

Note que você pode escrever uma lista com objetos em um arquivo... e depois lê-lo de volta em uma lista...
https://stackoverflow.com/questions/10654236/java-save-object-data-to-a-file

**Comment by AlessanBass** [comment]
A estratégia utilizada para apresentar os dados da maneira como o usuário deseja, foi bem simples porém eficiente. Ela foi executada em 4 passos que serão detalhados abaixo:

### 1° Leitura do arquivo 
Para realizar a leitura do arquivo, foi utilizada a classe **FileReader()** em conjunto com a classe **BufferedReader()**.  Em um **while** temos o método **ready()** que retorna verdadeiro enquanto tiver dados para serem lidos. Com o auxílio de uma variável **String linha** atribuímos a essa  variável o   método **readLine()** que retorna a linha atual lida e passa o cursor para a próxima linha.
```
 public void teste(File arq) throws IOException {
         FileReader fr = new FileReader(arq);
         BufferedReader br = new BufferedReader(fr);
         while (br.ready()){
         String linha = br.readLine();
        /*    Código aqui  */
     }
         br.close();
}
```
### 2° Tratamento de uma linha lida
Será necessário realizar uma espécie de divisão nessa linha que foi lida, já que ela contém os dados inseridos pelo usuário e ele deseja que esses dados sejam exibidos separadamente. E para isso foi utilizado o método **split()** que quebra uma string e retorna um vetor de substrings, porém é necessário informar um parâmetro pelo qual ele possa realizar essa divisão e o parâmetro escolhido foi **";"** . Abaixo tem um pedaço do código onde após cadastrar cada dado inserido pelo usuário, também é inserido um ";".
* ### Pedaço de código da classe Escrita 
   ``` public void escreveNoArquivo(File arq) throws IOException {
        FileWriter fw = new FileWriter(arq, true);
        fw.write(gastos.getNome()); //Salva o nome
        fw.write(";"); // Logo após o parâmetro para que mais tarde fosse possível realizar o tratamento  
        fw.write(gastos.getValor());
        fw.write(";"); //Parâmetro
        fw.write(gp.getNumDeParcelas());
        fw.write(";"); //Parâmetro
        fw.write(gp.getParcelasPagas());
        fw.write(";");//Parâmetro
        fw.write("\n"); //Após finalizar a inserção de dados do usuário é inserido uma quebra de linha para indicar fim da linha.
        fw.flush();
        fw.close();
    }
  ``` 
* ### Exemplo de como o arquivo é salvo
**ATENÇÃO: Observem que existe um padrão no qual os dados são salvos no arquivo.**
* **1° Nome da despesa**
* **2° Valor da despesa**
* **3° Quantidade do parcelamento**
* **4° Quantidade de parcelas pagas**

  ```
    Mercado;350.00;2;0;
    Shopping;150.00;2;0;
  ```

Sendo assim agora podemos realizar as operações necessárias para alocar as informações em variáveis para  realizar as manipulações. Foi criado um vetor nomeado de **separador** que recebe **linha.split(";")**, ou seja, recebe a linha já dividida pelo método split. 
```
 public void teste(File arq) throws IOException {
         FileReader fr = new FileReader(arq);
         BufferedReader br = new BufferedReader(fr);
         while (br.ready()){
         String linha = br.readLine();
         String [] separador = linha.split(";");
        /*    Código aqui  */
     }
         br.close();
}
```
### 3° Conversão de String -> Double 
Como estamos lendo uma linha e dividindo ela em partes do tipo String, será necessário fazer a conversão de alguns valores para que seja possível realizar algumas operações matemáticas. Para isso temos que criar variáveis que vão receber cada parte em que a linha foi dividida. E essas variáveis auxiliares vão receber o método **Double.parseDouble()**  que faz a conversão do tipo String para Double.  
```
 public void teste(File arq) throws IOException {
         FileReader fr = new FileReader(arq);
         BufferedReader br = new BufferedReader(fr);
         while (br.ready()){
         String linha = br.readLine();
         String [] separador = linha.split(";");
         //Convertendo String para Double
          double valor = Double.parseDouble(separador[1]);
          double parcelasPagas = Double.parseDouble(separador[3]);
          double numeroDeParcelas = Double.parseDouble(separador[2]);
        /*    Código aqui  */
     }
         br.close();
}
```
* **ATENÇÃO: É importante salientar que cada variável auxiliar recebe a posição do vetor relativa ao seu dado. Observem que na posição [0] do vetor contém  o nome da despesa (pois existe um padrão em que os dados são inseridos no arquivo) portanto não necessita ser convertido pois o nome somente será exibido na tela junto com as demais informações.** 

### 4° Apresentação dos dados para o usuário
Finalmente podemos exibir os dados de forma clara para o usuário. Temos mais alguns detalhes como a criação da variável **soma**  que será utilizada para realizar o cálculo da valor total a ser pago naquele mês e a variável **valorParcela** que armazena o valor da parcela caso a compra tenha sido parcelada.

```
 public void teste(File arq) throws IOException {
         FileReader fr = new FileReader(arq);
         BufferedReader br = new BufferedReader(fr);
         double soma = 0;
         while (br.ready()){
         String linha = br.readLine();
         String [] separador = linha.split(";");
         //Convertendo String para Double
          double valor = Double.parseDouble(separador[1]);
          double parcelasPagas = Double.parseDouble(separador[3]);
          double numeroDeParcelas = Double.parseDouble(separador[2]);
          double  valorParcela=0;

          System.out.println("Nome do gasto: "+separador[0]);
          System.out.println("Valor do Gasto: "+ separador[1]);
          System.out.printf("Parcelas: %.0f/%.0f\n", parcelasPagas, numeroDeParcelas);
            if (parcelasPagas == numeroDeParcelas){
                System.out.printf("Valor da %.0f parcela: %.2f\n", numeroDeParcelas, valorParcela = valor/numeroDeParcelas);
            } else {
                System.out.printf("Valor da %.0f parcela: %.2f\n", parcelasPagas+1, valorParcela = valor/numeroDeParcelas);
             }
           valor = valorParcela;
           soma += valor;
            System.out.println("-----------------------------");
     }
          System.out.printf("=== Valor Total: R$ %.2f ===\n\n",soma);
         br.close();
}
```
Commit referente: 0bfe68c900a2a8e1470672301583266938f23aaf
